Allow specifying the `verify` parameter for requests
rapidpro/rapidpro-python pull request #47
Opened 2017-03-23 11:28 UTC by rgaudin

Hey, more of a question than a PR at this time.
Currently there's no way to bypass SSL verification of requests made by the client.
I have a particular use case where the rapidpro server is using a self-signed certificate on a private network.

I believe it's harmless to offer people the opportunity to set this requests flag (`verify`) which can either be `True` (default), `False` (No SSL verification) or a path to a CA bundle file to which the server certificate would be verified upon.

See [requests' advanced section](http://docs.python-requests.org/en/latest/user/advanced/) for more info.

I haven't added support for the `cert` parameter which is client-side certificate to establish SSL connection with as I have no need for this at the moment and it seems overkill.

Let me know how you feel about adding support for `verify` and how should that `TembaClient` parameter be named.

2017-03-23 14:14 UTC, rowanseymour requested changes
Seems fine. Just fix missing coverage and rename param

2017-03-23 14:14 UTC, rowanseymour commented on temba_client/clients.py
> +    def __init__(self, host, token, api_version, user_agent=None, verify=None):
Let's rename this to something like `verify_ssl` so clearer what this is for.

2017-03-31 12:35 UTC, rgaudin commented
@rowanseymour ?

2017-03-31 12:37 UTC, rowanseymour approved these changes

2017-03-31 12:37 UTC, merged

2017-03-31 12:46 UTC, rowanseymour commented
Merged and released as 2.1.7. Thanks!